"use client";
/* eslint-disable jsx-a11y/media-has-caption -- Teacher transcript is rendered separately only when release is enabled. */

import { ReactNode, useEffect, useRef, useState } from "react";
import type { ListeningQuestion, ListeningTrack } from "./listening-types";

type Props = { attemptId: string; tracks: ListeningTrack[]; questions: ListeningQuestion[]; editable: boolean; apiUrl: string; accessToken: string; partNumber: number; renderQuestion: (question: ListeningQuestion, questionNumber: number) => ReactNode };

function ListeningPlayer({ attemptId, track, editable, apiUrl, accessToken }: { attemptId: string; track: ListeningTrack; editable: boolean; apiUrl: string; accessToken: string }) {
  const [source, setSource] = useState(""); const [playCount, setPlayCount] = useState(track.playCount ?? 0); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const lastAllowedTime = useRef(0); const sourceRef = useRef("");
  useEffect(() => () => { if (sourceRef.current) URL.revokeObjectURL(sourceRef.current); }, []);
  const exhausted = editable && track.maxPlayCount !== null && playCount >= track.maxPlayCount;
  async function start() { setBusy(true); setError(""); try { const response = await fetch(`${apiUrl}/student/assignment-attempts/${attemptId}/listening-tracks/${track.id}/play`, { method: "POST", headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(Array.isArray(body?.message) ? body.message.join(" ") : body?.message ?? "Không thể phát Listening."); } const nextCount = Number(response.headers.get("X-Listening-Play-Count")); if (Number.isFinite(nextCount)) setPlayCount(nextCount); if (sourceRef.current) URL.revokeObjectURL(sourceRef.current); const url = URL.createObjectURL(await response.blob()); sourceRef.current = url; lastAllowedTime.current = 0; setSource(url); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  function finish() { if (sourceRef.current) URL.revokeObjectURL(sourceRef.current); sourceRef.current = ""; setSource(""); lastAllowedTime.current = 0; }
  return <div className="student-listening-player"><div className="listening-play-status"><span>{track.maxPlayCount === null ? `Đã nghe ${playCount} lượt · Không giới hạn` : `Đã nghe ${playCount}/${track.maxPlayCount} lượt`}</span><span>{track.allowSeeking ? "Cho phép tua" : "Không cho phép tua"}</span></div>{source ? <audio autoPlay controls controlsList="nodownload noplaybackrate" preload="auto" src={source} onTimeUpdate={(event) => { if (!event.currentTarget.seeking) lastAllowedTime.current = event.currentTarget.currentTime; }} onSeeking={(event) => { if (!track.allowSeeking && Math.abs(event.currentTarget.currentTime - lastAllowedTime.current) > 1) event.currentTarget.currentTime = lastAllowedTime.current; }} onEnded={finish}>Trình duyệt không hỗ trợ phát âm thanh.</audio> : <button type="button" disabled={busy || exhausted || !track.audioReady} onClick={() => void start()}>{busy ? "Đang tải Listening..." : exhausted ? "Đã hết lượt nghe" : editable ? "▶ Bắt đầu nghe" : "▶ Nghe lại"}</button>}{error && <p className="grade-save-status error">{error}</p>}</div>;
}

export default function StudentListeningSection({ attemptId, tracks, questions, editable, apiUrl, accessToken, partNumber, renderQuestion }: Props) {
  const orderedQuestions = [...questions].sort((left, right) => left.position - right.position);
  const numberById = new Map(orderedQuestions.map((question, index) => [question.id, index + 1]));
  return <section className="assignment-question-part listening-part"><header className="assignment-part-heading"><span>PHẦN {partNumber}</span><h2>Listening</h2></header><div className="student-listening">{[...tracks].sort((left, right) => left.position - right.position).map((track, index) => <article className="student-listening-track" key={track.id}><header><span>LISTENING {index + 1}</span><h3>{track.title}</h3>{track.instructions && <p>{track.instructions}</p>}</header><ListeningPlayer attemptId={attemptId} track={track} editable={editable} apiUrl={apiUrl} accessToken={accessToken} />{track.transcript && <details className="listening-transcript"><summary>Transcript sau khi nộp bài</summary><p>{track.transcript}</p></details>}<div className="student-question-list">{orderedQuestions.filter((question) => question.listeningTrackId === track.id).map((question) => renderQuestion(question, numberById.get(question.id) ?? question.position + 1))}</div></article>)}</div></section>;
}
