"use client";

import { useEffect, useState } from "react";

type Item = { id: string; title: string; summary: string | null; status: string; updatedAt: string; session: { scheduledStart: string; classroom: { id: string; name: string; code: string } } };
type Detail = Item & { mainContent: string | null; theory: string | null; vocabulary: string | null; grammar: string | null; examples: string | null; reviewNotes: string | null; homeworkNotes: string | null; attachments: { id: string; fileName: string; fileType: string; fileSize: number; category: string; downloadUrl: string }[] };
const date = (value: string) => new Date(value).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" });
const sections: [keyof Detail, string][] = [["summary", "Tóm tắt"], ["mainContent", "Nội dung chính"], ["theory", "Lý thuyết"], ["vocabulary", "Từ vựng"], ["grammar", "Ngữ pháp"], ["examples", "Ví dụ"], ["reviewNotes", "Nội dung cần ôn"], ["homeworkNotes", "Bài tập / chuẩn bị buổi sau"]];

export default function StudentLessonViewer({ apiUrl, accessToken, onBack }: { apiUrl: string; accessToken: string; onBack: () => void }) {
  const [items, setItems] = useState<Item[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [classroomId, setClassroomId] = useState(""); const [error, setError] = useState(""); const headers = { Authorization: `Bearer ${accessToken}` };
  useEffect(() => { const params = new URLSearchParams({ month, pageSize: "100" }); if (classroomId) params.set("classroomId", classroomId); fetch(`${apiUrl}/student/lessons?${params}`, { headers: { Authorization: `Bearer ${accessToken}` } }).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (!response.ok) throw new Error(body.message); setItems(body.items); }).catch((reason: Error) => setError(reason.message)); }, [apiUrl, accessToken, month, classroomId]);
  async function open(id: string) { const response = await fetch(`${apiUrl}/student/lessons/${id}`, { headers }); const body = await response.json(); if (response.ok) setDetail(body); else setError(body.message); }
  async function download(item: Detail["attachments"][number]) { const response = await fetch(`${apiUrl}${item.downloadUrl}`, { headers }); if (!response.ok) { setError("Không thể tải tài liệu."); return; } const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = item.fileName; anchor.click(); URL.revokeObjectURL(url); }
  const classrooms = [...new Map(items.map((item) => [item.session.classroom.id, item.session.classroom])).values()];
  return <div className="student-lessons"><div className="manager-heading"><div><button className="back-link" onClick={detail ? () => setDetail(null) : onBack}>← {detail ? "Danh sách bài học" : "Tổng quan"}</button><p className="eyebrow">Bài học</p><h1>{detail?.title ?? "Bài học của tôi"}</h1></div></div>{error && <p className="admin-error">{error}</p>}{detail ? <article className="student-lesson-detail"><p className="lesson-detail-meta">{date(detail.session.scheduledStart)} · {detail.session.classroom.name}</p>{sections.map(([key, label]) => detail[key] ? <section key={key}><h2>{label}</h2><p>{String(detail[key])}</p></section> : null)}<section><h2>Tài liệu</h2>{detail.attachments.map((item) => <button className="student-attachment" key={item.id} onClick={() => void download(item)}><b>{item.fileName}</b><small>{item.category} · {(item.fileSize / 1024).toFixed(0)} KB</small></button>)}{!detail.attachments.length && <p>Chưa có tài liệu đính kèm.</p>}</section><footer>Cập nhật lần cuối: {date(detail.updatedAt)}</footer></article> : <><div className="lesson-filters student-lesson-filters"><select value={classroomId} onChange={(e) => setClassroomId(e.target.value)}><option value="">Tất cả lớp</option>{classrooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></div><div className="student-lesson-list">{items.map((item) => <article key={item.id}><time>{new Date(item.session.scheduledStart).toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit", timeZone: "Asia/Ho_Chi_Minh" })}</time><div><span>{item.session.classroom.name}</span><h2>{item.title}</h2><p>{item.summary ?? "Mở bài học để xem nội dung chi tiết."}</p><small>Đã cập nhật {date(item.updatedAt)}</small></div><button onClick={() => void open(item.id)}>Xem bài học</button></article>)}{!items.length && <p className="report-empty">Chưa có bài học nào được xuất bản.</p>}</div></>}</div>;
}
