"use client";

import { useEffect, useRef, useState } from "react";
import type { WritingSubmission, WritingTask } from "./writing-types";
import { writingTypeLabels } from "./writing-types";

type Props = { attemptId: string; task: WritingTask; submission: WritingSubmission | null; editable: boolean; apiUrl: string; accessToken: string; partNumber: number; onChanged: (submission: WritingSubmission) => void; onSavingChange: (saving: boolean) => void };
const countWords = (value: string) => value.trim() ? value.trim().split(/\s+/u).length : 0;

export default function StudentWritingSection({ attemptId, task, submission, editable, apiUrl, accessToken, partNumber, onChanged, onSavingChange }: Props) {
  const [essay, setEssay] = useState(submission?.essayContent ?? "");
  const [answers, setAnswers] = useState<Record<string, string>>(Object.fromEntries((submission?.translationAnswers ?? []).map((answer) => [answer.translationItemId, answer.answerText])));
  const [states, setStates] = useState<Record<string, string>>({}); const timers = useRef(new Map<string, number>()); const pendingSaves = useRef(0); const submissionRef = useRef(submission);
  useEffect(() => { submissionRef.current = submission; setEssay(submission?.essayContent ?? ""); setAnswers(Object.fromEntries((submission?.translationAnswers ?? []).map((answer) => [answer.translationItemId, answer.answerText]))); }, [submission]);
  useEffect(() => { const active = timers.current; return () => { active.forEach((timer) => window.clearTimeout(timer)); onSavingChange(false); }; }, [onSavingChange]);
  async function api<T>(path: string, body: object) { const response = await fetch(`${apiUrl}${path}`, { method: "PUT", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json().catch(() => null); if (!response.ok) throw new Error(Array.isArray(value?.message) ? value.message.join(" ") : value?.message ?? "Không thể lưu Writing."); return value as T; }
  function schedule(key: string, save: () => Promise<void>) { const current = timers.current.get(key); if (current) window.clearTimeout(current); setStates((value) => ({ ...value, [key]: "Đang lưu..." })); onSavingChange(true); timers.current.set(key, window.setTimeout(() => { timers.current.delete(key); pendingSaves.current += 1; void save().finally(() => { pendingSaves.current -= 1; onSavingChange(timers.current.size > 0 || pendingSaves.current > 0); }); }, 800)); }
  function updateEssay(value: string) { setEssay(value); schedule("essay", async () => { try { const saved = await api<WritingSubmission>(`/student/assignment-attempts/${attemptId}/writing/essay`, { content: value }); submissionRef.current = saved; onChanged(saved); setStates((state) => ({ ...state, essay: "✓ Đã lưu" })); } catch (reason) { setStates((state) => ({ ...state, essay: (reason as Error).message || "Không thể lưu. Vui lòng thử lại." })); } }); }
  function updateTranslation(itemId: string, value: string) { setAnswers((current) => ({ ...current, [itemId]: value })); schedule(itemId, async () => { try { const saved = await api<{ id: string; answerText: string }>(`/student/assignment-attempts/${attemptId}/writing/translation/${itemId}`, { answerText: value }); const current = submissionRef.current; const next: WritingSubmission = current ? { ...current, translationAnswers: [...current.translationAnswers.filter((answer) => answer.translationItemId !== itemId), { id: saved.id, translationItemId: itemId, answerText: saved.answerText, isCorrect: null, teacherComment: null }] } : { id: "", essayContent: null, wordCount: null, submittedAt: null, essayScore: null, teacherFeedback: null, gradedAt: null, translationAnswers: [{ id: saved.id, translationItemId: itemId, answerText: saved.answerText, isCorrect: null, teacherComment: null }], translationResult: null }; submissionRef.current = next; onChanged(next); setStates((state) => ({ ...state, [itemId]: "✓ Đã lưu" })); } catch (reason) { setStates((state) => ({ ...state, [itemId]: (reason as Error).message || "Không thể lưu" })); } }); }
  const result = submission?.translationResult;
  return <section className="assignment-question-part writing-part"><header className="assignment-part-heading"><span>PHẦN {partNumber}</span><h2>Writing</h2></header><div className="student-writing"><p className="section-kicker">{writingTypeLabels[task.type]}</p><h2>{task.title || writingTypeLabels[task.type]}</h2>{task.prompt && <p className="writing-prompt">{task.prompt}</p>}{task.instructions && <p className="writing-instructions">{task.instructions}</p>}
    {task.type === "ESSAY" ? <><textarea className="student-essay-input" disabled={!editable} rows={12} value={essay} onChange={(event) => updateEssay(event.target.value)} placeholder="Nhập bài viết của bạn..." /><div className="writing-save-row"><span>{countWords(essay)}{task.maxWords != null ? ` / ${task.maxWords}` : ""} từ{task.minWords != null ? ` · Tối thiểu ${task.minWords}` : ""}</span><b>{states.essay}</b></div>{!editable && <div className="writing-result-card"><strong>Essay</strong>{submission?.essayScore === null || submission?.essayScore === undefined ? <span>Chờ giáo viên chấm</span> : <span>{submission.essayScore}/10</span>}{submission?.teacherFeedback && <p><b>Nhận xét của giáo viên:</b> {submission.teacherFeedback}</p>}</div>}</> : <><div className="student-translation-list">{task.translationItems.map((item, index) => { const graded = submission?.translationAnswers.find((answer) => answer.translationItemId === item.id); return <article key={item.id}><header><b>Câu {index + 1}</b>{!editable && <span className={graded?.isCorrect === true ? "correct" : graded?.isCorrect === false ? "wrong" : ""}>{graded?.isCorrect === true ? "Đúng" : graded?.isCorrect === false ? "Sai" : "Chờ chấm"}</span>}</header><p>{item.sourceText}</p><textarea disabled={!editable} rows={3} value={answers[item.id] ?? ""} onChange={(event) => updateTranslation(item.id, event.target.value)} placeholder="Nhập câu dịch..." />{editable && <small>{states[item.id]}</small>}{!editable && graded?.teacherComment && <small><b>Nhận xét:</b> {graded.teacherComment}</small>}</article>; })}</div>{!editable && <div className="writing-result-card"><strong>{writingTypeLabels[task.type]}</strong>{result?.complete ? <span>{result.correctCount}/{result.totalItems} câu đúng · {result.percentage?.toFixed(1)}%</span> : <span>{result?.gradedCount ? `Đã chấm ${result.gradedCount}/${result.totalItems} câu` : "Chờ giáo viên chấm"}</span>}{submission?.teacherFeedback && <p><b>Nhận xét chung:</b> {submission.teacherFeedback}</p>}</div>}</>}
  </div></section>;
}
