"use client";

import { useState } from "react";
import type { WritingSubmission, WritingTask } from "./writing-types";
import { writingTypeLabels } from "./writing-types";

type Props = { assignmentId: string; task: WritingTask; submission: WritingSubmission | null; apiUrl: string; accessToken: string; onChanged: (submission: WritingSubmission) => void };

export default function TeacherWritingGrading({ assignmentId, task, submission, apiUrl, accessToken, onChanged }: Props) {
  const [score, setScore] = useState(submission?.essayScore?.toString() ?? ""); const [feedback, setFeedback] = useState(submission?.teacherFeedback ?? ""); const [comments, setComments] = useState<Record<string, string>>(Object.fromEntries((submission?.translationAnswers ?? []).map((answer) => [answer.id, answer.teacherComment ?? ""]))); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function api<T>(path: string, init?: RequestInit) { const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json", ...init?.headers } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(Array.isArray(body?.message) ? body.message.join(" ") : body?.message ?? "Không thể lưu đánh giá Writing."); return body as T; }
  async function gradeEssay() { if (!submission) return; setBusy("essay"); setError(""); setMessage(""); try { const value = await api<WritingSubmission>(`/assignments/${assignmentId}/writing/submissions/${submission.id}/essay-grade`, { method: "PATCH", body: JSON.stringify({ score: Number(score), feedback: feedback || null }) }); onChanged(value); setMessage(`✓ Đã lưu đánh giá lúc ${new Date(value.gradedAt!).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}.`); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function gradeAnswer(answerId: string, isCorrect: boolean) { if (!submission) return; setBusy(answerId); setError(""); setMessage(""); try { const value = await api<WritingSubmission>(`/assignments/${assignmentId}/writing/submissions/${submission.id}/translation/${answerId}`, { method: "PATCH", body: JSON.stringify({ isCorrect, teacherComment: comments[answerId] || null }) }); onChanged(value); setMessage("✓ Đã lưu đánh giá câu dịch."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function saveFeedback() { if (!submission) return; setBusy("feedback"); setError(""); try { const value = await api<WritingSubmission>(`/assignments/${assignmentId}/writing/submissions/${submission.id}/feedback`, { method: "PATCH", body: JSON.stringify({ feedback: feedback || null }) }); onChanged(value); setMessage("✓ Đã lưu nhận xét chung."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  return <article className="writing-grading"><header><span>WRITING · {writingTypeLabels[task.type].toUpperCase()}</span><b>{!submission ? "Chưa nộp" : task.type === "ESSAY" ? submission.essayScore === null ? "Chờ chấm" : "Đã chấm" : submission.translationResult?.complete ? "Đã chấm" : `Đã chấm ${submission.translationResult?.gradedCount ?? 0}/${task.translationItems.length} câu`}</b></header>{!submission ? <p>Học sinh chưa nộp phần Writing.</p> : task.type === "ESSAY" ? <><div className="submitted-essay"><h3>{task.title || "Essay"}</h3><p>{submission.essayContent}</p><small>{submission.wordCount ?? 0} từ · Nộp lúc {submission.submittedAt ? new Date(submission.submittedAt).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" }) : "—"}</small></div><label>Điểm <span>/ 10</span><input type="number" min="0" max="10" step="0.25" value={score} onChange={(event) => setScore(event.target.value)} /></label><label>Nhận xét chung<textarea rows={4} value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><button disabled={Boolean(busy) || score === ""} onClick={() => void gradeEssay()}>{busy === "essay" ? "Đang lưu..." : "Lưu đánh giá"}</button></> : <><div className="translation-grading-list">{task.translationItems.map((item, index) => { const answer = submission.translationAnswers.find((entry) => entry.translationItemId === item.id); return <section key={item.id}><header><b>Câu {index + 1}</b><span className={answer?.isCorrect === true ? "correct" : answer?.isCorrect === false ? "wrong" : ""}>{answer?.isCorrect === true ? "Đúng" : answer?.isCorrect === false ? "Sai" : "Chưa chấm"}</span></header><p><strong>Đề:</strong> {item.sourceText}</p><p><strong>Học sinh:</strong> {answer?.answerText || "—"}</p><p><strong>Đáp án tham khảo:</strong> {item.referenceAnswer || "Không có"}</p>{answer && <><label>Nhận xét<textarea rows={2} value={comments[answer.id] ?? ""} onChange={(event) => setComments({ ...comments, [answer.id]: event.target.value })} /></label><div><button disabled={Boolean(busy)} onClick={() => void gradeAnswer(answer.id, true)}>✓ Đúng</button><button disabled={Boolean(busy)} className="danger-link" onClick={() => void gradeAnswer(answer.id, false)}>✕ Sai</button></div></>}</section>; })}</div><label>Nhận xét chung<textarea rows={4} value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><button disabled={Boolean(busy)} onClick={() => void saveFeedback()}>{busy === "feedback" ? "Đang lưu..." : "Lưu nhận xét chung"}</button></>}{message && <p className="grade-save-status success">{message}</p>}{error && <p className="grade-save-status error">{error}</p>}</article>;
}
