"use client";

import { FormEvent, useState } from "react";
import type { TranslationItem, WritingTask, WritingTaskType } from "./writing-types";
import { writingTypeLabels } from "./writing-types";

type Props = { assignmentId: string; task: WritingTask | null; draft: boolean; apiUrl: string; accessToken: string; onChanged: () => Promise<void> };
const empty = { type: "ESSAY" as WritingTaskType, title: "", prompt: "", instructions: "", minWords: "100", maxWords: "150" };

export default function TeacherWritingEditor({ assignmentId, task, draft, apiUrl, accessToken, onChanged }: Props) {
  const [enabled, setEnabled] = useState(Boolean(task));
  const [form, setForm] = useState(task ? { type: task.type, title: task.title ?? "", prompt: task.prompt ?? "", instructions: task.instructions ?? "", minWords: task.minWords?.toString() ?? "", maxWords: task.maxWords?.toString() ?? "" } : empty);
  const [newItem, setNewItem] = useState({ sourceText: "", referenceAnswer: "" });
  const [edits, setEdits] = useState<Record<string, { sourceText: string; referenceAnswer: string }>>(Object.fromEntries((task?.translationItems ?? []).map((item) => [item.id, { sourceText: item.sourceText, referenceAnswer: item.referenceAnswer ?? "" }])));
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function api<T>(path: string, init?: RequestInit) { const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json", ...init?.headers } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(Array.isArray(body?.message) ? body.message.join(" ") : body?.message ?? "Không thể lưu Writing."); return body as T; }
  async function saveTask(event?: FormEvent) { event?.preventDefault(); setBusy("task"); setError(""); try { await api(`/assignments/${assignmentId}/writing`, { method: "PUT", body: JSON.stringify({ type: form.type, title: form.title || null, prompt: form.prompt || null, instructions: form.instructions || null, minWords: form.type === "ESSAY" && form.minWords !== "" ? Number(form.minWords) : null, maxWords: form.type === "ESSAY" && form.maxWords !== "" ? Number(form.maxWords) : null }) }); setMessage("✓ Đã lưu cấu hình Writing."); await onChanged(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function toggle(value: boolean) { setEnabled(value); setMessage(""); setError(""); if (!value && task) { if (!confirm("Tắt Writing sẽ xóa cấu hình Writing của bản nháp này.")) { setEnabled(true); return; } setBusy("disable"); try { await api(`/assignments/${assignmentId}/writing`, { method: "DELETE" }); await onChanged(); setMessage("✓ Đã tắt Writing."); } catch (reason) { setEnabled(true); setError((reason as Error).message); } finally { setBusy(""); } } }
  async function addItem(event: FormEvent) { event.preventDefault(); setBusy("add-item"); setError(""); try { await api(`/assignments/${assignmentId}/writing/translation-items`, { method: "POST", body: JSON.stringify(newItem) }); setNewItem({ sourceText: "", referenceAnswer: "" }); await onChanged(); setMessage("✓ Đã thêm câu dịch."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function saveItem(item: TranslationItem) { const value = edits[item.id]; if (!value) return; setBusy(item.id); try { await api(`/assignments/${assignmentId}/writing/translation-items/${item.id}`, { method: "PATCH", body: JSON.stringify(value) }); await onChanged(); setMessage("✓ Đã lưu câu dịch."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function removeItem(item: TranslationItem) { if (!confirm("Xóa câu dịch này?")) return; setBusy(item.id); try { await api(`/assignments/${assignmentId}/writing/translation-items/${item.id}`, { method: "DELETE" }); await onChanged(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  async function moveItem(index: number, direction: number) { if (!task) return; const ids = task.translationItems.map((item) => item.id); const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target]!, ids[index]!]; setBusy("reorder"); try { await api(`/assignments/${assignmentId}/writing/translation-items/reorder`, { method: "POST", body: JSON.stringify({ ids }) }); await onChanged(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } }
  return <section className="writing-editor"><div className="assignment-section-title"><div><p className="section-kicker">BÀI WRITING</p><h2>Writing</h2></div></div><label className="assignment-section-toggle"><input type="checkbox" disabled={!draft || Boolean(busy)} checked={enabled} onChange={(event) => void toggle(event.target.checked)} />Có bài Writing</label>
    {enabled && <form className="writing-task-form" onSubmit={(event) => void saveTask(event)}><label>Loại bài Writing<select disabled={!draft} value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as WritingTaskType })}>{Object.entries(writingTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Tiêu đề<input disabled={!draft} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label>{form.type === "ESSAY" && <label>Đề bài<textarea disabled={!draft} required rows={5} value={form.prompt} onChange={(event) => setForm({ ...form, prompt: event.target.value })} /></label>}<label>Hướng dẫn<textarea disabled={!draft} rows={3} value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} /></label>{form.type === "ESSAY" && <div className="writing-word-limits"><label>Số từ tối thiểu<input disabled={!draft} type="number" min="0" value={form.minWords} onChange={(event) => setForm({ ...form, minWords: event.target.value })} /></label><label>Số từ tối đa<input disabled={!draft} type="number" min="0" value={form.maxWords} onChange={(event) => setForm({ ...form, maxWords: event.target.value })} /></label><div className="writing-max-score"><span>Điểm tối đa</span><strong>10 điểm</strong></div></div>}{draft && <button disabled={Boolean(busy)}>{busy === "task" ? "Đang lưu..." : "Lưu Writing"}</button>}</form>}
    {enabled && form.type !== "ESSAY" && task && <div className="translation-item-editor"><h3>Danh sách câu dịch</h3>{task.translationItems.map((item, index) => { const edit = edits[item.id] ?? { sourceText: item.sourceText, referenceAnswer: item.referenceAnswer ?? "" }; return <article key={item.id}><header><b>Câu {index + 1}</b><div><button type="button" disabled={!draft || !index || Boolean(busy)} onClick={() => void moveItem(index, -1)}>↑</button><button type="button" disabled={!draft || index === task.translationItems.length - 1 || Boolean(busy)} onClick={() => void moveItem(index, 1)}>↓</button><button type="button" className="danger-link" disabled={!draft || Boolean(busy)} onClick={() => void removeItem(item)}>Xóa</button></div></header><label>Nội dung câu<textarea disabled={!draft} rows={2} value={edit.sourceText} onChange={(event) => setEdits({ ...edits, [item.id]: { ...edit, sourceText: event.target.value } })} /></label><label>Đáp án tham khảo<textarea disabled={!draft} rows={2} value={edit.referenceAnswer} onChange={(event) => setEdits({ ...edits, [item.id]: { ...edit, referenceAnswer: event.target.value } })} /></label>{draft && <button type="button" disabled={Boolean(busy)} onClick={() => void saveItem(item)}>{busy === item.id ? "Đang lưu..." : "Lưu câu"}</button>}</article>; })}{draft && <form className="translation-add-form" onSubmit={(event) => void addItem(event)}><label>Câu mới<textarea required rows={2} value={newItem.sourceText} onChange={(event) => setNewItem({ ...newItem, sourceText: event.target.value })} /></label><label>Đáp án tham khảo<textarea rows={2} value={newItem.referenceAnswer} onChange={(event) => setNewItem({ ...newItem, referenceAnswer: event.target.value })} /></label><button disabled={Boolean(busy)}>{busy === "add-item" ? "Đang thêm..." : "+ Thêm câu"}</button></form>}</div>}
    {message && <p className="grade-save-status success">{message}</p>}{error && <p className="grade-save-status error">{error}</p>}
  </section>;
}
