import "dotenv/config";
import type { INestApplication } from "@nestjs/common";
import { JwtModule, JwtService } from "@nestjs/jwt";
import { Test } from "@nestjs/testing";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, describe, test } from "node:test";
import request from "supertest";
import { AssignmentQuestionType, AssignmentSection, AssignmentStatus, AssignmentType } from "../../../generated/prisma/client";
import { RolesGuard } from "../src/access/roles.guard";
import { TeacherApprovalRepository } from "../src/access/teacher-approval-access";
import { AssignmentController } from "../src/assignments/assignment.controller";
import { AssignmentRepository } from "../src/assignments/assignment.repository";
import { AssignmentService } from "../src/assignments/assignment.service";
import type { AssignmentInput, AssignmentListQuery, AssignmentPatch, AnswerInput, PassageInput, QuestionInput, ReorderInput } from "../src/assignments/assignment.types";
import { gradeQuestion, studentConfig } from "../src/assignments/grading";
import { AuthRepository } from "../src/auth/auth.repository";
import type { AuthUser, AuthUserWithPassword } from "../src/auth/auth.types";
import { JwtAuthGuard } from "../src/auth/jwt-auth.guard";
import { authConfig } from "../src/config/env";

class TestAuth extends AuthRepository {
  constructor(private readonly users: AuthUser[]) { super(); }
  async findUserById(id: string) { return this.users.find((item) => item.id === id) ?? null; }
  async createUser(): Promise<AuthUser> { throw new Error("unused"); } async findUserByEmail(): Promise<AuthUserWithPassword | null> { return null; } async verifyEmail(): Promise<AuthUser | null> { return null; } async createRefreshToken() {} async rotateRefreshToken(): Promise<AuthUser | null> { return null; } async revokeRefreshToken() {}
}

type StoredQuestion = QuestionInput & { id: string; position: number };
type StoredAssignment = AssignmentInput & { id: string; ownerId: string; status: AssignmentStatus; questions: StoredQuestion[]; attempts: string[]; publishedAt: string | null; closedAt: string | null; readAloudRequired?: boolean };
type StoredAttempt = { id: string; assignmentId: string; studentId: string; attemptNumber: number; status: "IN_PROGRESS" | "AUTO_GRADED"; answers: Map<string, unknown>; score?: number; maxScore: number; percentage?: number; isLate: boolean; hasRecording?: boolean };

class MemoryAssignments extends AssignmentRepository {
  readonly assignments = new Map<string, StoredAssignment>(); readonly attempts = new Map<string, StoredAttempt>(); readonly audits: string[] = [];
  constructor(readonly owner: string, readonly classroomId: string, readonly enrolled: string) { super(); }
  view(item: StoredAssignment, student = false) { return { ...item, classroom: { id: item.classroomId, name: "English A1", code: "MSN-A1" }, lesson: null, passages: [], questions: item.questions.map((question) => student ? { ...question, config: studentConfig(question.type, question.config), explanation: undefined } : question), attemptCount: item.attempts.length }; }
  async listTeacher(teacherId: string, query: AssignmentListQuery) { const items = [...this.assignments.values()].filter((item) => item.ownerId === teacherId).map((item) => this.view(item)); return { items, total: items.length, page: query.page, pageSize: query.pageSize, totalPages: 1 }; }
  async create(teacherId: string, input: AssignmentInput) { if (teacherId !== this.owner || input.classroomId !== this.classroomId) return { status: "NOT_FOUND" as const }; const item: StoredAssignment = { ...input, id: randomUUID(), ownerId: teacherId, status: AssignmentStatus.DRAFT, questions: [], attempts: [], publishedAt: null, closedAt: null }; this.assignments.set(item.id, item); this.audits.push("ASSIGNMENT_CREATED"); return { status: "OK" as const, value: this.view(item) }; }
  async teacherDetail(teacherId: string, id: string) { const item = this.assignments.get(id); return item?.ownerId === teacherId ? { status: "OK" as const, value: this.view(item) } : { status: "NOT_FOUND" as const }; }
  async update(teacherId: string, id: string, input: AssignmentPatch) { const item = this.assignments.get(id); if (!item || item.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; if (item.status !== AssignmentStatus.DRAFT) return { status: "INVALID_STATE" as const }; Object.assign(item, input); return { status: "OK" as const, value: this.view(item) }; }
  async transition(teacherId: string, id: string, action: "publish" | "close" | "archive") { const item = this.assignments.get(id); if (!item || item.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; const expected = action === "publish" ? AssignmentStatus.DRAFT : action === "close" ? AssignmentStatus.PUBLISHED : AssignmentStatus.CLOSED; if (item.status !== expected) return { status: "INVALID_STATE" as const }; if (action === "publish" && !item.questions.length) return { status: "INVALID" as const, message: "Cần có câu hỏi." }; item.status = action === "publish" ? AssignmentStatus.PUBLISHED : action === "close" ? AssignmentStatus.CLOSED : AssignmentStatus.ARCHIVED; if (action === "publish") item.publishedAt = new Date().toISOString(); if (action === "close") item.closedAt = new Date().toISOString(); this.audits.push(`ASSIGNMENT_${item.status}`); return { status: "OK" as const, value: this.view(item) }; }
  async delete(teacherId: string, id: string) { const item = this.assignments.get(id); if (!item || item.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; if (item.status !== AssignmentStatus.DRAFT || item.attempts.length) return { status: "INVALID_STATE" as const }; this.assignments.delete(id); this.audits.push("ASSIGNMENT_DELETED"); return { status: "OK" as const, value: { success: true } }; }
  async addQuestion(teacherId: string, id: string, input: QuestionInput) { const item = this.assignments.get(id); if (!item || item.ownerId !== teacherId || item.status !== AssignmentStatus.DRAFT) return { status: "NOT_FOUND" as const }; const question = { ...input, id: randomUUID(), position: item.questions.length }; item.questions.push(question); return { status: "OK" as const, value: question }; }
  async updateQuestion(teacherId: string, id: string, questionId: string, input: QuestionInput) { const item = this.assignments.get(id); const question = item?.questions.find((entry) => entry.id === questionId); if (!item || item.ownerId !== teacherId || !question) return { status: "NOT_FOUND" as const }; Object.assign(question, input); return { status: "OK" as const, value: question }; }
  async deleteQuestion(teacherId: string, id: string, questionId: string) { const item = this.assignments.get(id); if (!item || item.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; item.questions = item.questions.filter((question) => question.id !== questionId); return { status: "OK" as const, value: { success: true } }; }
  async reorderQuestions(teacherId: string, id: string, input: ReorderInput) { void teacherId; void id; void input; return { status: "OK" as const, value: { success: true } }; }
  async addPassage(_teacherId: string, _id: string, input: PassageInput) { return { status: "OK" as const, value: { id: randomUUID(), ...input } }; }
  async updatePassage(_teacherId: string, _id: string, passageId: string, input: PassageInput) { return { status: "OK" as const, value: { id: passageId, ...input } }; }
  async deletePassage() { return { status: "OK" as const, value: { success: true } }; } async reorderPassages() { return { status: "OK" as const, value: { success: true } }; }
  async results() { return { status: "OK" as const, value: { summary: {}, students: [] } }; } async studentResults() { return { status: "OK" as const, value: [] }; } async teacherAttempt() { return { status: "NOT_FOUND" as const }; }
  async listStudent(studentId: string, query: AssignmentListQuery) { const items = studentId === this.enrolled ? [...this.assignments.values()].filter((item) => item.status !== AssignmentStatus.DRAFT).map((item) => ({ ...this.view(item, true), questions: undefined })) : []; return { items, total: items.length, page: query.page, pageSize: query.pageSize, totalPages: 1 }; }
  async studentDetail(studentId: string, id: string) { const item = this.assignments.get(id); return item && studentId === this.enrolled && item.status !== AssignmentStatus.DRAFT ? { status: "OK" as const, value: { ...this.view(item, true), questions: undefined } } : { status: "NOT_FOUND" as const }; }
  async startAttempt(studentId: string, id: string) { const item = this.assignments.get(id); if (!item || studentId !== this.enrolled || item.status !== AssignmentStatus.PUBLISHED) return { status: "NOT_FOUND" as const }; const current = [...this.attempts.values()].find((attempt) => attempt.assignmentId === id && attempt.studentId === studentId && attempt.status === "IN_PROGRESS"); if (current) return { status: "OK" as const, value: this.attemptView(current, item) }; if (item.attempts.length >= item.maxAttempts) return { status: "LIMIT" as const }; const attempt: StoredAttempt = { id: randomUUID(), assignmentId: id, studentId, attemptNumber: item.attempts.length + 1, status: "IN_PROGRESS", answers: new Map(), maxScore: item.questions.reduce((sum, question) => sum + question.points, 0), isLate: false }; item.attempts.push(attempt.id); this.attempts.set(attempt.id, attempt); return { status: "OK" as const, value: this.attemptView(attempt, item) }; }
  async studentAttempt(studentId: string, id: string) { const attempt = this.attempts.get(id); const item = attempt ? this.assignments.get(attempt.assignmentId) : null; return attempt && item && attempt.studentId === studentId ? { status: "OK" as const, value: this.attemptView(attempt, item) } : { status: "NOT_FOUND" as const }; }
  async saveAnswer(studentId: string, id: string, questionId: string, input: AnswerInput) { const attempt = this.attempts.get(id); if (!attempt || attempt.studentId !== studentId || attempt.status !== "IN_PROGRESS") return { status: "NOT_FOUND" as const }; attempt.answers.set(questionId, input.answer); return { status: "OK" as const, value: { questionId, answer: input.answer } }; }
  async submit(studentId: string, id: string) { const attempt = this.attempts.get(id); const item = attempt ? this.assignments.get(attempt.assignmentId) : null; if (!attempt || !item || attempt.studentId !== studentId) return { status: "NOT_FOUND" as const }; if (attempt.status === "AUTO_GRADED") return { status: "OK" as const, value: this.attemptView(attempt, item) }; if (item.readAloudRequired && !attempt.hasRecording) return { status: "INVALID" as const, message: "Bạn cần hoàn thành bài đọc ghi âm trước khi nộp bài." }; attempt.score = item.questions.reduce((sum, question) => sum + gradeQuestion(question, attempt.answers.get(question.id)).awardedPoints, 0); attempt.percentage = attempt.maxScore ? attempt.score / attempt.maxScore * 100 : 0; attempt.status = "AUTO_GRADED"; attempt.isLate = Boolean(item.dueAt && new Date() > new Date(item.dueAt)); return { status: "OK" as const, value: this.attemptView(attempt, item) }; }
  private attemptView(attempt: StoredAttempt, item: StoredAssignment) { const show = attempt.status === "AUTO_GRADED" && item.showScoreImmediately; return { id: attempt.id, assignmentId: item.id, attemptNumber: attempt.attemptNumber, status: attempt.status, isLate: attempt.isLate, assignment: this.view(item, true), answers: [...attempt.answers].map(([questionId, answer]) => ({ questionId, answer })), ...(show ? { score: attempt.score, maxScore: attempt.maxScore, percentage: attempt.percentage } : {}) }; }
}

describe("Assignment API", () => {
  let app: INestApplication; let server: Parameters<typeof request>[0]; let jwt: JwtService; let repository: MemoryAssignments; let assignmentId = ""; let questionId = "";
  const owner = randomUUID(), other = randomUUID(), unapproved = randomUUID(), student = randomUUID(), outsider = randomUUID(), classroom = randomUUID();
  const users: AuthUser[] = [{ id: owner, email: "owner@test", phone: null, fullName: "Owner", status: "ACTIVE", roles: ["TEACHER"] }, { id: other, email: "other@test", phone: null, fullName: "Other", status: "ACTIVE", roles: ["TEACHER"] }, { id: unapproved, email: "pending@test", phone: null, fullName: "Pending", status: "ACTIVE", roles: ["TEACHER"] }, { id: student, email: "student@test", phone: null, fullName: "Student", status: "ACTIVE", roles: ["STUDENT"] }, { id: outsider, email: "out@test", phone: null, fullName: "Out", status: "ACTIVE", roles: ["STUDENT"] }];
  before(async () => { repository = new MemoryAssignments(owner, classroom, student); const moduleRef = await Test.createTestingModule({ imports: [JwtModule.register({ secret: authConfig.accessSecret() })], controllers: [AssignmentController], providers: [AssignmentService, JwtAuthGuard, RolesGuard, { provide: TeacherApprovalRepository, useValue: { isApproved: async (id: string) => id !== unapproved } }, { provide: AuthRepository, useValue: new TestAuth(users) }, { provide: AssignmentRepository, useValue: repository }] }).compile(); app = moduleRef.createNestApplication(); await app.init(); server = app.getHttpServer(); jwt = moduleRef.get(JwtService); });
  after(async () => { await app.close(); });
  async function auth(id: string) { const user = users.find((item) => item.id === id)!; return `Bearer ${await jwt.signAsync({ sub: user.id, email: user.email, roles: user.roles }, { secret: authConfig.accessSecret(), issuer: authConfig.accessIssuer(), audience: authConfig.accessAudience(), expiresIn: 900 })}`; }
  const assignment = { classroomId: classroom, lessonId: null, title: "Vocabulary unit 1", description: null, type: AssignmentType.HOMEWORK, dueAt: null, allowLateSubmission: false, maxAttempts: 1, showScoreImmediately: true };
  const question = { type: AssignmentQuestionType.VOCAB_MULTIPLE_CHOICE, section: AssignmentSection.VOCABULARY, passageId: null, prompt: "Apple means?", explanation: "Apple = quả táo", points: 2, required: true, config: { options: [{ id: "a", text: "Quả cam" }, { id: "b", text: "Quả táo" }], correctOptionId: "b" } };

  test("approved owner creates and edits while unapproved/unauthorized teachers are denied", async () => { const created = await request(server).post("/assignments").set("Authorization", await auth(owner)).send(assignment).expect(201); assignmentId = created.body.id; await request(server).patch(`/assignments/${assignmentId}`).set("Authorization", await auth(owner)).send({ title: "Updated title" }).expect(200); await request(server).post("/assignments").set("Authorization", await auth(unapproved)).send(assignment).expect(403); await request(server).get(`/assignments/${assignmentId}`).set("Authorization", await auth(other)).expect(404); });
  test("validates questions and refuses publishing an empty assignment", async () => { await request(server).post(`/assignments/${assignmentId}/publish`).set("Authorization", await auth(owner)).expect(400); await request(server).post(`/assignments/${assignmentId}/questions`).set("Authorization", await auth(owner)).send({ ...question, config: { options: [{ id: "a", text: "Only" }], correctOptionId: "a" } }).expect(400); const added = await request(server).post(`/assignments/${assignmentId}/questions`).set("Authorization", await auth(owner)).send(question).expect(201); questionId = added.body.id; await request(server).patch(`/assignments/${assignmentId}/questions/${questionId}`).set("Authorization", await auth(owner)).send({ ...question, prompt: "Apple là gì?" }).expect(200); await request(server).post(`/assignments/${assignmentId}/publish`).set("Authorization", await auth(owner)).expect(201); });
  test("only enrolled students see published assignments and no answer key leaks", async () => { const visible = await request(server).get("/student/assignments").set("Authorization", await auth(student)).expect(200); assert.equal(visible.body.items.length, 1); const serialized = JSON.stringify(visible.body); assert.equal(serialized.includes("correctOptionId"), false); await request(server).get(`/student/assignments/${assignmentId}`).set("Authorization", await auth(outsider)).expect(404); });
  test("starts, autosaves, resumes, grades and idempotently submits only own attempts", async () => { const started = await request(server).post(`/student/assignments/${assignmentId}/attempts`).set("Authorization", await auth(student)).expect(201); const attemptId = started.body.id as string; await request(server).put(`/student/assignment-attempts/${attemptId}/answers/${questionId}`).set("Authorization", await auth(student)).send({ answer: { selectedOptionId: "b" } }).expect(200); await request(server).post(`/student/assignments/${assignmentId}/attempts`).set("Authorization", await auth(student)).expect(201).expect(({ body }) => assert.equal(body.id, attemptId)); await request(server).post(`/student/assignment-attempts/${attemptId}/submit`).set("Authorization", await auth(outsider)).expect(404); const submitted = await request(server).post(`/student/assignment-attempts/${attemptId}/submit`).set("Authorization", await auth(student)).expect(201); assert.equal(submitted.body.score, 2); const duplicate = await request(server).post(`/student/assignment-attempts/${attemptId}/submit`).set("Authorization", await auth(student)).expect(201); assert.equal(duplicate.body.score, 2); await request(server).post(`/student/assignments/${assignmentId}/attempts`).set("Authorization", await auth(student)).expect(409); });
  test("honors hidden scores, late grading and lifecycle/delete rules", async () => { const hidden = await repository.create(owner, { ...assignment, title: "Hidden", dueAt: new Date(Date.now() - 60_000).toISOString(), allowLateSubmission: true, showScoreImmediately: false }); const id = (hidden as { value: { id: string } }).value.id; const q = await repository.addQuestion(owner, id, question); await repository.transition(owner, id, "publish"); const attempt = await repository.startAttempt(student, id); const attemptValue = (attempt as { value: { id: string } }).value; await repository.saveAnswer(student, attemptValue.id, (q as { value: { id: string } }).value.id, { answer: { selectedOptionId: "b" } }); const result = await repository.submit(student, attemptValue.id); assert.equal("score" in (result as { value: object }).value, false); assert.equal((result as { value: { isLate: boolean } }).value.isLate, true); await request(server).post(`/assignments/${assignmentId}/close`).set("Authorization", await auth(owner)).expect(201); await request(server).post(`/assignments/${assignmentId}/archive`).set("Authorization", await auth(owner)).expect(201); await request(server).delete(`/assignments/${assignmentId}`).set("Authorization", await auth(owner)).expect(409); const draft = await repository.create(owner, { ...assignment, title: "Delete me" }); await request(server).delete(`/assignments/${(draft as { value: { id: string } }).value.id}`).set("Authorization", await auth(owner)).expect(200); assert.ok(repository.audits.includes("ASSIGNMENT_DELETED")); });
  test("blocks final submission when a required read-aloud recording is missing", async () => { const created = await repository.create(owner, { ...assignment, title: "Read aloud required" }); const item = repository.assignments.get((created as { value: { id: string } }).value.id)!; item.readAloudRequired = true; await repository.addQuestion(owner, item.id, question); await repository.transition(owner, item.id, "publish"); const started = await request(server).post(`/student/assignments/${item.id}/attempts`).set("Authorization", await auth(student)).expect(201); await request(server).post(`/student/assignment-attempts/${started.body.id}/submit`).set("Authorization", await auth(student)).expect(400).expect(({ body }) => assert.match(body.message, /ghi âm/)); });
});
