import "dotenv/config";
import type { INestApplication } from "@nestjs/common";
import { JwtModule, JwtService } from "@nestjs/jwt";
import { Test } from "@nestjs/testing";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, test } from "node:test";
import request from "supertest";
import { Role } from "../../../generated/prisma/client";
import { RolesGuard } from "../src/access/roles.guard";
import { TeacherApprovalRepository } from "../src/access/teacher-approval-access";
import { AuthRepository } from "../src/auth/auth.repository";
import type { AuthUser, AuthUserWithPassword } from "../src/auth/auth.types";
import { JwtAuthGuard } from "../src/auth/jwt-auth.guard";
import { authConfig } from "../src/config/env";
import { ReadAloudController } from "../src/assignments/read-aloud.controller";
import { ReadAloudRepository, type ReadAloudAudioInput, type ReadAloudAudioRecord, type ReadAloudResult, type ReadAloudTaskInput } from "../src/assignments/read-aloud.repository";
import { ReadAloudService } from "../src/assignments/read-aloud.service";
import { ReadAloudStorageService } from "../src/assignments/read-aloud-storage.service";

class TestAuth extends AuthRepository {
  constructor(private readonly users: AuthUser[]) { super(); }
  async findUserById(id: string) { return this.users.find((item) => item.id === id) ?? null; }
  async createUser(): Promise<AuthUser> { throw new Error("unused"); } async findUserByEmail(): Promise<AuthUserWithPassword | null> { return null; } async verifyEmail(): Promise<AuthUser | null> { return null; } async createRefreshToken() {} async rotateRefreshToken(): Promise<AuthUser | null> { return null; } async revokeRefreshToken() {}
}

type Submission = { id: string; studentId: string; attemptId: string; storageKey: string; fileName: string; fileType: string; durationSeconds: number | null; submitted: boolean; score: number | null; feedback: string | null };
class MemoryReadAloud extends ReadAloudRepository {
  task: (ReadAloudTaskInput & { id: string; assignmentId: string }) | null = null; submissions = new Map<string, Submission>(); inProgress = true; audits: string[] = [];
  constructor(readonly owner: string, readonly assignment: string, readonly student: string, readonly attempt: string) { super(); }
  async upsertTask(teacherId: string, assignmentId: string, input: ReadAloudTaskInput): Promise<ReadAloudResult> { if (teacherId !== this.owner || assignmentId !== this.assignment) return { status: "NOT_FOUND" }; this.task = { ...input, id: this.task?.id ?? randomUUID(), assignmentId }; this.audits.push("ASSIGNMENT_READ_ALOUD_ENABLED"); return { status: "OK", value: this.task }; }
  async deleteTask(teacherId: string, assignmentId: string): Promise<ReadAloudResult> { if (teacherId !== this.owner || assignmentId !== this.assignment || !this.task) return { status: "NOT_FOUND" }; this.task = null; return { status: "OK", value: { success: true } }; }
  async studentTask(studentId: string, assignmentId: string): Promise<ReadAloudResult> { return studentId === this.student && assignmentId === this.assignment && this.task ? { status: "OK", value: this.task } : { status: "NOT_FOUND" }; }
  async saveUpload(studentId: string, attemptId: string, input: ReadAloudAudioInput): Promise<ReadAloudResult<{ submission: unknown; oldStorageKey: string | null }>> { if (studentId !== this.student || attemptId !== this.attempt || !this.task) return { status: "NOT_FOUND" }; if (!this.inProgress) return { status: "INVALID_STATE" }; if (input.durationSeconds && input.durationSeconds > (this.task.maxDurationSeconds ?? 300)) return { status: "INVALID", message: "Bản ghi quá dài." }; const old = this.submissions.get(attemptId); const item: Submission = { id: old?.id ?? randomUUID(), studentId, attemptId, storageKey: input.storageKey, fileName: input.fileName, fileType: input.fileType, durationSeconds: input.durationSeconds ?? null, submitted: false, score: null, feedback: null }; this.submissions.set(attemptId, item); return { status: "OK", value: { submission: { ...item, storageKey: undefined, audioUrl: `/assignment-read-aloud-submissions/${item.id}/audio` }, oldStorageKey: old?.storageKey ?? null } }; }
  async audio(userId: string, roles: Role[], submissionId: string): Promise<ReadAloudAudioRecord | null> { const item = [...this.submissions.values()].find((entry) => entry.id === submissionId); if (!item || !(roles.includes(Role.ADMIN) || userId === item.studentId || roles.includes(Role.TEACHER) && userId === this.owner)) return null; return { storageKey: item.storageKey, fileName: item.fileName, fileType: item.fileType }; }
  async audioForAttempt(studentId: string, attemptId: string): Promise<ReadAloudAudioRecord | null> { const item = this.submissions.get(attemptId); return item?.studentId === studentId ? { storageKey: item.storageKey, fileName: item.fileName, fileType: item.fileType } : null; }
  async results(teacherId: string, assignmentId: string): Promise<ReadAloudResult> { if (teacherId !== this.owner || assignmentId !== this.assignment || !this.task) return { status: "NOT_FOUND" }; return { status: "OK", value: { task: this.task, students: [] } }; }
  async grade(teacherId: string, assignmentId: string, submissionId: string, score: number, feedback?: string | null): Promise<ReadAloudResult> { const item = [...this.submissions.values()].find((entry) => entry.id === submissionId); if (teacherId !== this.owner || assignmentId !== this.assignment || !item || !this.task) return { status: "NOT_FOUND" }; if (score < 0 || score > this.task.maxScore) return { status: "INVALID", message: `Điểm đọc phải từ 0 đến ${this.task.maxScore}.` }; item.score = score; item.feedback = feedback ?? null; this.audits.push("ASSIGNMENT_READ_ALOUD_GRADED"); return { status: "OK", value: item }; }
}

describe("Assignment read-aloud API", () => {
  let app: INestApplication; let server: Parameters<typeof request>[0]; let jwt: JwtService; let repository: MemoryReadAloud; let uploadDirectory = ""; let submissionId = "";
  const owner = randomUUID(), other = randomUUID(), unapproved = randomUUID(), student = randomUUID(), outsider = randomUUID(), admin = randomUUID(), assignment = randomUUID(), attempt = randomUUID();
  const users: AuthUser[] = [{ id: owner, email: "owner@audio.test", phone: null, fullName: "Owner", status: "ACTIVE", roles: ["TEACHER"] }, { id: other, email: "other@audio.test", phone: null, fullName: "Other", status: "ACTIVE", roles: ["TEACHER"] }, { id: unapproved, email: "pending@audio.test", phone: null, fullName: "Pending", status: "ACTIVE", roles: ["TEACHER"] }, { id: student, email: "student@audio.test", phone: null, fullName: "Student", status: "ACTIVE", roles: ["STUDENT"] }, { id: outsider, email: "outsider@audio.test", phone: null, fullName: "Outsider", status: "ACTIVE", roles: ["STUDENT"] }, { id: admin, email: "admin@audio.test", phone: null, fullName: "Admin", status: "ACTIVE", roles: ["ADMIN"] }];
  before(async () => { uploadDirectory = await mkdtemp(join(tmpdir(), "msngan-read-aloud-test-")); process.env.ASSIGNMENT_UPLOAD_DIR = uploadDirectory; repository = new MemoryReadAloud(owner, assignment, student, attempt); const moduleRef = await Test.createTestingModule({ imports: [JwtModule.register({ secret: authConfig.accessSecret() })], controllers: [ReadAloudController], providers: [ReadAloudService, ReadAloudStorageService, JwtAuthGuard, RolesGuard, { provide: TeacherApprovalRepository, useValue: { isApproved: async (id: string) => id !== unapproved } }, { provide: AuthRepository, useValue: new TestAuth(users) }, { provide: ReadAloudRepository, useValue: repository }] }).compile(); app = moduleRef.createNestApplication(); await app.init(); server = app.getHttpServer(); jwt = moduleRef.get(JwtService); });
  after(async () => { await app.close(); await rm(uploadDirectory, { recursive: true, force: true }); });
  async function auth(id: string) { const user = users.find((item) => item.id === id)!; return `Bearer ${await jwt.signAsync({ sub: user.id, email: user.email, roles: user.roles }, { secret: authConfig.accessSecret(), issuer: authConfig.accessIssuer(), audience: authConfig.accessAudience(), expiresIn: 900 })}`; }
  const task = { title: "Read unit 1", readingText: "Hello, my name is An.", instructions: "Đọc rõ ràng.", maxScore: 10, maxDurationSeconds: 60 };
  const webm = Buffer.from([0x1a, 0x45, 0xdf, 0xa3, 0x01, 0x02, 0x03]);

  test("approved owner enables a valid task while invalid, unapproved and unauthorized requests are rejected", async () => { await request(server).put(`/assignments/${assignment}/read-aloud`).set("Authorization", await auth(owner)).send({ ...task, readingText: "" }).expect(400); await request(server).put(`/assignments/${assignment}/read-aloud`).set("Authorization", await auth(unapproved)).send(task).expect(403); await request(server).put(`/assignments/${assignment}/read-aloud`).set("Authorization", await auth(other)).send(task).expect(404); await request(server).put(`/assignments/${assignment}/read-aloud`).set("Authorization", await auth(owner)).send(task).expect(200); assert.ok(repository.audits.includes("ASSIGNMENT_READ_ALOUD_ENABLED")); });
  test("only enrolled student sees the requirement", async () => { await request(server).get(`/student/assignments/${assignment}/read-aloud`).set("Authorization", await auth(student)).expect(200).expect(({ body }) => assert.equal(body.readingText, task.readingText)); await request(server).get(`/student/assignments/${assignment}/read-aloud`).set("Authorization", await auth(outsider)).expect(404); });
  test("uploads and replaces supported browser audio without exposing storage paths", async () => { const first = await request(server).post(`/student/assignment-attempts/${attempt}/read-aloud/upload`).set("Authorization", await auth(student)).field("durationSeconds", "12").attach("file", webm, { filename: "reading.webm", contentType: "audio/webm" }).expect(201); submissionId = first.body.id; assert.equal(first.body.storageKey, undefined); const second = await request(server).post(`/student/assignment-attempts/${attempt}/read-aloud/upload`).set("Authorization", await auth(student)).field("durationSeconds", "13").attach("file", webm, { filename: "reading.webm", contentType: "audio/webm" }).expect(201); assert.equal(second.body.id, submissionId); await request(server).post(`/student/assignment-attempts/${attempt}/read-aloud/upload`).set("Authorization", await auth(student)).attach("file", Buffer.from("bad"), { filename: "bad.exe", contentType: "application/octet-stream" }).expect(400); });
  test("streams audio only to the owner student, authorized teacher and admin", async () => { for (const id of [student, owner, admin]) await request(server).get(`/assignment-read-aloud-submissions/${submissionId}/audio`).set("Authorization", await auth(id)).expect(200).expect("Content-Type", /audio\/webm/); await request(server).get(`/assignment-read-aloud-submissions/${submissionId}/audio`).set("Authorization", await auth(outsider)).expect(404); await request(server).get(`/student/assignment-attempts/${attempt}/read-aloud/audio`).set("Authorization", await auth(student)).expect(200); });
  test("rejects replacement after submission and validates manual score", async () => { repository.inProgress = false; await request(server).post(`/student/assignment-attempts/${attempt}/read-aloud/upload`).set("Authorization", await auth(student)).attach("file", webm, { filename: "reading.webm", contentType: "audio/webm" }).expect(409); await request(server).patch(`/assignments/${assignment}/read-aloud/submissions/${submissionId}/grade`).set("Authorization", await auth(other)).send({ score: 8 }).expect(404); await request(server).patch(`/assignments/${assignment}/read-aloud/submissions/${submissionId}/grade`).set("Authorization", await auth(owner)).send({ score: 11 }).expect(400); await request(server).patch(`/assignments/${assignment}/read-aloud/submissions/${submissionId}/grade`).set("Authorization", await auth(owner)).send({ score: 8.5, feedback: "Đọc rõ." }).expect(200); assert.ok(repository.audits.includes("ASSIGNMENT_READ_ALOUD_GRADED")); });
  test("storage rejects oversized files before writing", () => { const storage = app.get(ReadAloudStorageService); assert.throws(() => storage.validate({ originalname: "large.webm", mimetype: "audio/webm", size: 20 * 1024 * 1024 + 1, buffer: webm })); });
});
