import "dotenv/config";
import type { INestApplication } from "@nestjs/common";
import { JwtModule, JwtService } from "@nestjs/jwt";
import { Test } from "@nestjs/testing";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, describe, test } from "node:test";
import request from "supertest";
import { RolesGuard } from "../src/access/roles.guard";
import { TeacherApprovalRepository } from "../src/access/teacher-approval-access";
import { AuthRepository } from "../src/auth/auth.repository";
import type { AuthUser, AuthUserWithPassword } from "../src/auth/auth.types";
import { JwtAuthGuard } from "../src/auth/jwt-auth.guard";
import { authConfig } from "../src/config/env";
import { LessonController } from "../src/lessons/lesson.controller";
import { LessonRepository } from "../src/lessons/lesson.repository";
import { LessonService } from "../src/lessons/lesson.service";
import type { AttachmentInput, LessonListQuery, LessonTextInput } from "../src/lessons/lesson.types";
import { LessonStorageService } from "../src/lessons/storage/lesson-storage.service";

class TestAuth extends AuthRepository {
  constructor(private readonly users: AuthUser[]) { super(); }
  async findUserById(id: string) { return this.users.find((item) => item.id === id) ?? null; }
  async createUser(): Promise<AuthUser> { throw new Error("unused"); } async findUserByEmail(): Promise<AuthUserWithPassword | null> { return null; } async verifyEmail(): Promise<AuthUser | null> { return null; } async createRefreshToken() {} async rotateRefreshToken(): Promise<AuthUser | null> { return null; } async revokeRefreshToken() {}
}
type StoredLesson = { id: string; sessionId: string; ownerId: string; classroomId: string; status: "DRAFT" | "PUBLISHED" | "ARCHIVED"; title: string; summary: string | null; mainContent: string | null; theory: string | null; vocabulary: string | null; grammar: string | null; examples: string | null; reviewNotes: string | null; homeworkNotes: string | null; publishedAt: string | null; updatedAt: string; attachments: { id: string; storageKey: string; fileName: string; fileType: string; fileSize: number; category: string; downloadUrl: string }[] };

class MemoryLessons extends LessonRepository {
  readonly lessons = new Map<string, StoredLesson>(); readonly audits: string[] = []; readonly sessions = new Map<string, { ownerId: string; classroomId: string; title: string }>();
  constructor(private readonly enrolledStudent: string) { super(); }
  addSession(id: string, ownerId: string, classroomId: string, title: string, auto = false) { this.sessions.set(id, { ownerId, classroomId, title }); if (auto) this.ensure(ownerId, id); }
  private ensure(teacherId: string, sessionId: string) { const session = this.sessions.get(sessionId); if (!session || session.ownerId !== teacherId) return null; let lesson = this.lessons.get(sessionId); if (!lesson) { lesson = { id: randomUUID(), sessionId, ownerId: teacherId, classroomId: session.classroomId, status: "DRAFT", title: session.title, summary: null, mainContent: null, theory: null, vocabulary: null, grammar: null, examples: null, reviewNotes: null, homeworkNotes: null, publishedAt: null, updatedAt: new Date().toISOString(), attachments: [] }; this.lessons.set(sessionId, lesson); this.audits.push("LESSON_CREATED"); } return lesson; }
  private view(lesson: StoredLesson) { return { ...lesson, updatedBy: { fullName: "Teacher" }, session: { scheduledStart: new Date().toISOString(), classroom: { id: lesson.classroomId, name: "BigBear1", code: "MSN-BEAR" } }, attachments: lesson.attachments.map((item) => ({ id: item.id, fileName: item.fileName, fileType: item.fileType, fileSize: item.fileSize, category: item.category, downloadUrl: item.downloadUrl })) }; }
  async listTeacher(teacherId: string, query: LessonListQuery) { const items = [...this.sessions.entries()].filter(([, s]) => s.ownerId === teacherId).map(([id, s]) => ({ id, title: s.title, scheduledStart: new Date().toISOString(), classroom: { id: s.classroomId, name: "BigBear1", code: "MSN-BEAR" }, lesson: this.lessons.get(id) ?? null })); return { items, total: items.length, page: query.page, pageSize: query.pageSize, totalPages: 1 }; }
  async teacherLesson(teacherId: string, sessionId: string) { const lesson = this.ensure(teacherId, sessionId); return lesson ? { status: "OK" as const, value: this.view(lesson) } : { status: "NOT_FOUND" as const }; }
  async update(teacherId: string, sessionId: string, input: LessonTextInput) { const lesson = this.ensure(teacherId, sessionId); if (!lesson) return { status: "NOT_FOUND" as const }; Object.assign(lesson, input, { updatedAt: new Date().toISOString() }); this.audits.push("LESSON_UPDATED"); return { status: "OK" as const, value: this.view(lesson) }; }
  async publish(teacherId: string, sessionId: string) { const lesson = this.lessons.get(sessionId); if (!lesson || lesson.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; if (!lesson.summary && !lesson.attachments.length) return { status: "EMPTY" as const }; lesson.status = "PUBLISHED"; lesson.publishedAt ??= new Date().toISOString(); this.audits.push("LESSON_PUBLISHED"); return { status: "OK" as const, value: this.view(lesson) }; }
  async archive(teacherId: string, sessionId: string) { const lesson = this.lessons.get(sessionId); if (!lesson || lesson.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; lesson.status = "ARCHIVED"; this.audits.push("LESSON_ARCHIVED"); return { status: "OK" as const, value: this.view(lesson) }; }
  async addAttachment(teacherId: string, sessionId: string, input: AttachmentInput) { const lesson = this.ensure(teacherId, sessionId); if (!lesson) return { status: "NOT_FOUND" as const }; const item = { id: randomUUID(), ...input, downloadUrl: "" }; item.downloadUrl = `/lessons/attachments/${item.id}/download`; lesson.attachments.push(item); this.audits.push("LESSON_ATTACHMENT_UPLOADED"); return { status: "OK" as const, value: { id: item.id, fileName: item.fileName, fileType: item.fileType, fileSize: item.fileSize, category: item.category, downloadUrl: item.downloadUrl } }; }
  async attachmentForDelete(teacherId: string, sessionId: string, attachmentId: string) { const item = this.lessons.get(sessionId)?.ownerId === teacherId ? this.lessons.get(sessionId)?.attachments.find((a) => a.id === attachmentId) : null; return item ? { status: "OK" as const, storageKey: item.storageKey } : { status: "NOT_FOUND" as const }; }
  async deleteAttachment(teacherId: string, sessionId: string, attachmentId: string) { const lesson = this.lessons.get(sessionId); if (!lesson || lesson.ownerId !== teacherId) return { status: "NOT_FOUND" as const }; const index = lesson.attachments.findIndex((a) => a.id === attachmentId); if (index < 0) return { status: "NOT_FOUND" as const }; lesson.attachments.splice(index, 1); this.audits.push("LESSON_ATTACHMENT_DELETED"); return { status: "OK" as const, value: { success: true } }; }
  async listStudent(studentId: string, query: LessonListQuery) { const items = studentId === this.enrolledStudent ? [...this.lessons.values()].filter((l) => l.status !== "DRAFT").map((l) => this.view(l)) : []; return { items, total: items.length, page: query.page, pageSize: query.pageSize, totalPages: 1 }; }
  async studentLesson(studentId: string, lessonId: string) { const lesson = [...this.lessons.values()].find((l) => l.id === lessonId && l.status !== "DRAFT" && studentId === this.enrolledStudent); return lesson ? { status: "OK" as const, value: this.view(lesson) } : { status: "NOT_FOUND" as const }; }
  async adminLesson(lessonId: string) { const lesson = [...this.lessons.values()].find((item) => item.id === lessonId); return lesson ? { status: "OK" as const, value: this.view(lesson) } : { status: "NOT_FOUND" as const }; }
  async download(userId: string, roles: AuthUser["roles"], attachmentId: string) { const lesson = [...this.lessons.values()].find((l) => l.attachments.some((a) => a.id === attachmentId)); const item = lesson?.attachments.find((a) => a.id === attachmentId); if (!lesson || !item) return null; const allowed = roles.includes("ADMIN") || (roles.includes("TEACHER") && lesson.ownerId === userId) || (roles.includes("STUDENT") && userId === this.enrolledStudent && lesson.status !== "DRAFT"); return allowed ? { storageKey: item.storageKey, fileName: item.fileName, fileType: item.fileType } : null; }
}

describe("Lesson API", () => {
  let app: INestApplication; let server: Parameters<typeof request>[0]; let jwt: JwtService; let repository: MemoryLessons; let storage: LessonStorageService;
  const owner = randomUUID(), other = randomUUID(), unapproved = randomUUID(), student = randomUUID(), outsider = randomUUID(), admin = randomUUID(); const session = randomUUID(), historical = randomUUID();
  const users: AuthUser[] = [{ id: owner, email: "owner@test", phone: null, fullName: "Owner", status: "ACTIVE", roles: ["TEACHER"] }, { id: other, email: "other@test", phone: null, fullName: "Other", status: "ACTIVE", roles: ["TEACHER"] }, { id: unapproved, email: "pending@test", phone: null, fullName: "Pending", status: "ACTIVE", roles: ["TEACHER"] }, { id: student, email: "student@test", phone: null, fullName: "Student", status: "ACTIVE", roles: ["STUDENT"] }, { id: outsider, email: "out@test", phone: null, fullName: "Out", status: "ACTIVE", roles: ["STUDENT"] }, { id: admin, email: "admin@test", phone: null, fullName: "Admin", status: "ACTIVE", roles: ["ADMIN"] }];
  before(async () => { process.env.LESSON_UPLOAD_DIR = `/tmp/msngan-lessons-${randomUUID()}`; repository = new MemoryLessons(student); repository.addSession(session, owner, randomUUID(), "Unit 1", true); repository.addSession(historical, owner, randomUUID(), "Historical"); const moduleRef = await Test.createTestingModule({ imports: [JwtModule.register({ secret: authConfig.accessSecret() })], controllers: [LessonController], providers: [LessonService, LessonStorageService, JwtAuthGuard, RolesGuard, { provide: TeacherApprovalRepository, useValue: { isApproved: async (id: string) => id !== unapproved } }, { provide: AuthRepository, useValue: new TestAuth(users) }, { provide: LessonRepository, useValue: repository }] }).compile(); app = moduleRef.createNestApplication(); await app.init(); server = app.getHttpServer(); jwt = moduleRef.get(JwtService); storage = moduleRef.get(LessonStorageService); });
  after(async () => { await app.close(); });
  async function token(id: string) { const user = users.find((u) => u.id === id)!; return jwt.signAsync({ sub: user.id, email: user.email, roles: user.roles }, { secret: authConfig.accessSecret(), issuer: authConfig.accessIssuer(), audience: authConfig.accessAudience(), expiresIn: 900 }); }

  test("owner lazily creates once, edits at any time and published lesson remains editable", async () => { const auth = `Bearer ${await token(owner)}`; assert.equal(repository.lessons.size, 1); await request(server).get(`/sessions/${historical}/lesson`).set("Authorization", auth).expect(200); await request(server).get(`/sessions/${historical}/lesson`).set("Authorization", auth).expect(200); assert.equal(repository.lessons.size, 2); await request(server).put(`/sessions/${session}/lesson`).set("Authorization", auth).send({ summary: "Before/during/after content" }).expect(200); const first = await request(server).post(`/sessions/${session}/lesson/publish`).set("Authorization", auth).expect(201); const publishedAt = first.body.publishedAt; await request(server).put(`/sessions/${session}/lesson`).set("Authorization", auth).send({ summary: "Published update" }).expect(200).expect(({ body }) => assert.equal(body.publishedAt, publishedAt)); await request(server).post(`/sessions/${session}/lesson/archive`).set("Authorization", auth).expect(201); for (const action of ["LESSON_CREATED", "LESSON_UPDATED", "LESSON_PUBLISHED", "LESSON_ARCHIVED"]) assert.ok(repository.audits.includes(action)); });
  test("non-owner, unapproved teacher and student cannot mutate", async () => { await request(server).put(`/sessions/${session}/lesson`).set("Authorization", `Bearer ${await token(other)}`).send({ summary: "No" }).expect(404); await request(server).put(`/sessions/${session}/lesson`).set("Authorization", `Bearer ${await token(unapproved)}`).send({ summary: "No" }).expect(403); await request(server).put(`/sessions/${session}/lesson`).set("Authorization", `Bearer ${await token(student)}`).send({ summary: "No" }).expect(403); });
  test("students see published/archived but never draft or non-enrolled lessons", async () => { const published = repository.lessons.get(session)!; const draft = repository.lessons.get(historical)!; const auth = `Bearer ${await token(student)}`; published.status = "PUBLISHED"; await request(server).get(`/student/lessons/${published.id}`).set("Authorization", auth).expect(200); published.status = "ARCHIVED"; await request(server).get(`/student/lessons/${published.id}`).set("Authorization", auth).expect(200); await request(server).get(`/student/lessons/${draft.id}`).set("Authorization", auth).expect(404); await request(server).get(`/student/lessons/${published.id}`).set("Authorization", `Bearer ${await token(outsider)}`).expect(404); await request(server).get(`/admin/lessons/${draft.id}`).set("Authorization", `Bearer ${await token(admin)}`).expect(200); });
  test("validates, secures, downloads and deletes attachments without exposing storage keys", async () => { const auth = `Bearer ${await token(owner)}`; const pdf = await request(server).post(`/sessions/${session}/lesson/attachments`).set("Authorization", auth).attach("file", Buffer.from("%PDF-1.4 test"), { filename: "Grammar.pdf", contentType: "application/pdf" }).expect(201); assert.equal(pdf.body.storageKey, undefined); const id = pdf.body.id as string; await request(server).get(`/lessons/attachments/${id}/download`).set("Authorization", `Bearer ${await token(student)}`).expect(200); await request(server).get(`/lessons/attachments/${id}/download`).set("Authorization", `Bearer ${await token(admin)}`).expect(200); await request(server).get(`/lessons/attachments/${id}/download`).set("Authorization", `Bearer ${await token(outsider)}`).expect(404); await request(server).post(`/sessions/${session}/lesson/attachments`).set("Authorization", `Bearer ${await token(other)}`).attach("file", Buffer.from("%PDF-test"), { filename: "No.pdf", contentType: "application/pdf" }).expect(404); await request(server).post(`/sessions/${session}/lesson/attachments`).set("Authorization", auth).attach("file", Buffer.from("bad"), { filename: "bad.exe", contentType: "application/octet-stream" }).expect(400); const draftFile = await request(server).post(`/sessions/${historical}/lesson/attachments`).set("Authorization", auth).attach("file", Buffer.from("%PDF-draft"), { filename: "Draft.pdf", contentType: "application/pdf" }).expect(201); await request(server).get(`/lessons/attachments/${draftFile.body.id}/download`).set("Authorization", `Bearer ${await token(student)}`).expect(404); await request(server).delete(`/sessions/${historical}/lesson/attachments/${draftFile.body.id}`).set("Authorization", auth).expect(200); await request(server).delete(`/sessions/${session}/lesson/attachments/${id}`).set("Authorization", `Bearer ${await token(other)}`).expect(404); await request(server).delete(`/sessions/${session}/lesson/attachments/${id}`).set("Authorization", auth).expect(200); assert.ok(repository.audits.includes("LESSON_ATTACHMENT_UPLOADED") && repository.audits.includes("LESSON_ATTACHMENT_DELETED")); });

  test("accepts approved image and Office signatures and rejects MIME or oversized files", () => {
    const files = [
      { originalname: "photo.jpg", mimetype: "image/jpeg", buffer: Buffer.from([0xff, 0xd8, 0xff, 0x00]) },
      { originalname: "photo.png", mimetype: "image/png", buffer: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]) },
      { originalname: "photo.webp", mimetype: "image/webp", buffer: Buffer.from("RIFFxxxxWEBP") },
      { originalname: "sheet.docx", mimetype: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: Buffer.from([0x50, 0x4b, 0x03, 0x04]) },
      { originalname: "slides.pptx", mimetype: "application/vnd.openxmlformats-officedocument.presentationml.presentation", buffer: Buffer.from([0x50, 0x4b, 0x03, 0x04]) },
    ];
    for (const file of files) assert.doesNotThrow(() => storage.validate({ ...file, size: file.buffer.length }));
    assert.throws(() => storage.validate({ originalname: "fake.pdf", mimetype: "image/png", size: 4, buffer: Buffer.from("%PDF") }));
    assert.throws(() => storage.validate({ originalname: "huge.pdf", mimetype: "application/pdf", size: 10 * 1024 * 1024 + 1, buffer: Buffer.from("%PDF") }));
  });
});
